version: '2.1'
services:
  mongodb:
    image: chengkuan/mongodb-6.0.8:latest
    build:
      context: ./
      dockerfile: Dockerfile
    pull_policy: always
    ports:
     - 27017:27017
    healthcheck:
      test: 'mongosh localhost:27017/test --quiet'
      interval: 2s
      timeout: 20s
      retries: 10
    volumes:
      - /data/db
    environment:
     - MONGODB_ADMIN_USER=admin
     - MONGODB_USER=booking
     - MONGODB_ADMIN_PASSWORD=admin
     - MONGODB_PASSWORD=booking
     - MONGODB_DATABASE=booking
  