FROM chengkuan/etcd-backup-base:1.0.0

ARG KUBE_VERSION="v1.22.4"

RUN apk add --no-cache --virtual .temp-deps curl
RUN apk update \
    && curl -LO https://storage.googleapis.com/kubernetes-release/release/${KUBE_VERSION}/bin/linux/amd64/kubectl \
    && chmod +x ./kubectl \
    && mv ./kubectl /usr/local/bin/kubectl    
RUN apk del .temp-deps
